
INSERT INTO equipment (name, brand, category, price, stock_amount, image) VALUES
('70% Isopropyl Alcohol Wipe, 100/tub','Store Brand','First Aid ',3.49,5, 'Alcohol_Wipes.jpg'),
('Adhesive Bandages, Box of 100','McKesson','First Aid ',1.94,5, 'Adhesive_Bandages.jpg'),
('Adhesive Tape','3M','First Aid ',0.59,5, 'Adhesive_Tape.jpg' ),
('Basin, large','McKesson','Bath Safety & Urinals',9.94,5, 'Basin.jpg'),
('Bedpan','McKesson','Bath Safety & Urinals',1.94,5, 'Bedpan.jpg'),
('Biohazard Bags, Box of 50','Ultra-Tuff','Biohazard',5.94,5, 'BIohazard bags.jpg'),
('Blood Pressure Cuffs','Store Brand','General Healthcare',23.98,5, 'Bloodpressure_cuff.Jpg'),
('Colostomy Bag, Box of 20','Store Brand','Advance Medical Care',29.98,5, 'Colostomy_Bag.jpg'),
('Cotton Balls','Store Brand','Beauty',1.74,5, 'Cotton_Balls.JPG'),
('Cotton Tip Applicators, Box of 1000','Store Brand','Beauty',16.99,5, 'CottonTipApplicators.jpg'),
('Crutches (adult/youth)','McKesson','General Healthcare',11.94,5, 'Crutches.jpg'),
('Diapers (adult/child), Box of 50','Depend','Bath Safety & Urinals',29.98,5, 'Diapers.jpg'),
('Disposable Gowns, Box of 50','McKesson','Advance Medical Care',43.95,5, 'DisposableGowns.jpg'),
('Drainage Bag','Bard','Advance Medical Care',4.93,5, 'Drainage Bag.jpg'),
('Dressing Pads (large), Box of 50','Telfa','Advance Medical Care',9.59,5, 'Dressin_Pads.jpg'),
('Foley Catheters','Bard','Advance Medical Care',3.94,5, 'FoleyCath.jpg'),
('Gauze (2x2), Pack of 200','Telfa','Advance Medical Care',1.94,5, 'Gauze.jpg'),
('Gel Foam Hemostatic Agents','Pfizer Pharmaceutical','Advance Medical Care',199.99,5, 'GelFoam.jpg'),
('Gloves (Nonsterile-small, medium, large), Box of 100','McKesson','General Healthcare',4.99,5, 'NonsterileGloves.jpg'),
('Gloves (Sterile/surgical size 6-1/2, 7, 7-1/2, 8, 8-1/2), Box of 100','McKesson','General Healthcare',4.99,5, 'SterileGLoves.jpg'),
('Glucometer ','One Touch','Diabetic Care',19.98,5, 'Glucometer.jpg'),
('Glucometer Strips, Box of 50','One Touch','Diabetic Care',27.94,5, 'GlucoTeststrips.jpg'),
('Iodine Swabs, Box of 50','Telfa','Advance Medical Care',6.94,5, 'Iodine Swabs.jpg'),
('IV Catheters (size 14, 16, 18, 20, 22, and 24)','Bard','Advance Medical Care',2.94,5, 'IV catheters.jpg'),
('IV Fluid-Normal Saline/Lactated Ringers, Box of 35','Baxter','Needles/Syringes',174.49,5, 'IVFluid.jpg'),
('Lancets, Box of Ten','One Touch','Diabetic Care',6.69,5, 'lancets.jpg'),
('Liquid Soap, 64 fl oz','Softsoap','General Healthcare',12.75,5, 'liquidsoap.jpg' ),
('Lubrication Jelly, 4 oz tube, Box of 12','McKesson','General Healthcare',12.94,5, 'lubricationjelly.jpg'),
('Masks, disposable, box of 50','3M','General Healthcare',10.94,5, 'masks.jpg' ),
('Nasogastric Tubes/Feeding Tubes','Bard','Advance Medical Care',2.39,5, 'Nasogastric_Tubes.jpg'),
('Nebulizer Machine','Store Brand','Advance Medical Care',24.95,5, 'Nebulizer.jpg'),
('Nebulizer Tubing','Store Brand','Advance Medical Care',2.98,5, 'NebulizerTube.jpg'),
('O2 Masks (adult/pediatric)','Ocean','First Aid ',5.98,5, 'OS mask.jpg'),
('O2 Nasal Prongs (adult/pediatric)','ResMed','Advance Medical Care',104.99,5, 'O2nasalprongs.jpg'),
('O2 Tubing','Store Brand','Advance Medical Care',1.99,5, 'O2Tubing.jpg'),
('Otoscopes/Speculums','Welch Allyn','Advance Medical Care',18.99,5, 'Otoscopes.jpg'),
('Paracentesis Trays','Becton Dickenson','Advance Medical Care',74.99,5, 'paracentesistray.jpg'),
('Penrose Drains','Store Brand','Advance Medical Care',4.98,5, 'PenroseDrains.jpg'),
('PPV Masks/Ambu Bags','Allied Healthcare','Advance Medical Care',11.98,5, 'PPVMasks.jpg'),
('Pulse Oximeter (O2 sat machine)','Masimo','Advance Medical Care',749.94,5, 'PulseOximeter.jpg'),
('Rolled Bandages','Uline','First Aid ',6.99,5, 'Rolledbandage.jpg'),
('Scapel Blades/Disposable Scapels','Quartzy','Advance Medical Care',14.99,5, 'scapel blades.jpg'),
('Shoe Covers, disposable','Uline','Advance Medical Care',34.99,5, 'Shoecovers.jpg'),
('Specimen Containers','McKesson','Bath Safety & Urinals',4.94,5, 'Specimencontainers.jpg'),
('Sterile Rolled Gauze ','Kerlix','First Aid ',0.99,5, 'rolledgauze.jpg'),
('Stethoscopes','3M','General Healthcare',98.98,5, 'Stethoscopes.jpg'),
('Stool Containers','Medline','Advance Medical Care',17.94,5, 'stoolcontainers.JPG'),
('Suction Tubing','McKesson','Advance Medical Care',0.89,5, 'suctiontubing.jpg'),
('Suction, Yankauer Tips','Dynarex','Advance Medical Care',0.78,5, 'suctionyanktips.jpg'),
('Surgical Drapes','McKesson','Advance Medical Care',0.34,5, 'surgicaldrapes.jpg'),
('Surgical Gowns','Dynarex','Advance Medical Care',4.94,5, 'surgicalgowns.jpg'),
('Syringes, 10 ml','Quartzy','Advance Medical Care',19.98,5, 'Syringes.jpg'),
('Syringes, 3 ml','Quartzy','Advance Medical Care',13.68,5, 'Syringes.jpg'),
('Syringes, 5 ml','Quartzy','Advance Medical Care',16.98,5, 'Syringes.jpg'),
('Syringes, 60 ml, 40 pack','Quartzy','Advance Medical Care',22.98,5, 'Syringes.jpg'),
('Thermometers','McKesson','First Aid ',3.94,5, 'thermometer.jpg'),
('Tongue Depressors','McKesson','General Healthcare',5.49,5, 'tonguedepressers.jpg'),
('Tourniquets','McKesson','First Aid ',0.14,5, 'Tourniquets.jpg'),
('Urinals','Store Brand','Bath Safety & Urinals',0.94,5, 'urinals.jpg'),
('Urinary Bags','McKesson','Bath Safety & Urinals',1.94,5, 'urinarybags.jpg'),
('Wheelchairs','SpinLife','General Healthcare',178.99,5, 'wheelchair.jpg'),
('Wrist Braces','Store Brand','General Healthcare',12.99,5, 'wristbraces.jpg');
