<?php

return [

    'state' => [
        'AL'=>"Alabama",
        'AK'=>"Alaska",
        'AZ'=>"Arizona",
        'AR'=>"Arkansas",
        'CA'=>"California",
        'CO'=>"Colorado",
        'CT'=>"Connecticut",
        'DE'=>"Delaware",
        'DC'=>"District Of Columbia",
        'FL'=>"Florida",
        'GA'=>"Georgia",
        'HI'=>"Hawaii",
        'ID'=>"Idaho",
        'IL'=>"Illinois",
        'IN'=>"Indiana",
        'IA'=>"Iowa",
        'KS'=>"Kansas",
        'KY'=>"Kentucky",
        'LA'=>"Louisiana",
        'ME'=>"Maine",
        'MD'=>"Maryland",
        'MA'=>"Massachusetts",
        'MI'=>"Michigan",
        'MN'=>"Minnesota",
        'MS'=>"Mississippi",
        'MO'=>"Missouri",
        'MT'=>"Montana",
        'NE'=>"Nebraska",
        'NV'=>"Nevada",
        'NH'=>"New Hampshire",
        'NJ'=>"New Jersey",
        'NM'=>"New Mexico",
        'NY'=>"New York",
        'NC'=>"North Carolina",
        'ND'=>"North Dakota",
        'OH'=>"Ohio",
        'OK'=>"Oklahoma",
        'OR'=>"Oregon",
        'PA'=>"Pennsylvania",
        'RI'=>"Rhode Island",
        'SC'=>"South Carolina",
        'SD'=>"South Dakota",
        'TN'=>"Tennessee",
        'TX'=>"Texas",
        'UT'=>"Utah",
        'VT'=>"Vermont",
        'VA'=>"Virginia",
        'WA'=>"Washington",
        'WV'=>"West Virginia",
        'WI'=>"Wisconsin",
        'WY'=>"Wyoming"
    ],

    'month' => [
        'Jan'=>'01',
        'Feb'=>"02",
        'Mar'=>"03",
        'Apr'=>"04",
        'May'=>"05",
        'Jun'=>"06",
        'Jul'=>"07",
        'Aug'=>"08",
        'Sep'=>"09",
        'Oct'=>"10",
        'Nov'=>"11",
        'Dec'=>"12",
    ],

    'year'=> [
        '2019'=>"2019",
        '2020'=>"2020",
        '2021'=>"2021",
        '2022'=>"2022",
        '2023'=>"2023",
        '2024'=>"2024",
        '2025'=>"2025",
        '2026'=>"2026",
        '2027'=>"2027",
        '2028'=>"2028",
        '2029'=>"2029",
        '2030'=>"2030",
        '2031'=>"2031",
        '2032'=>"2032",
        '2033'=>"2033",
        '2034'=>"2034",
        '2035'=>"2035",
        '2036'=>"2036",
        '2037'=>"2037",
    ],
];
